services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 5s
      retries: 3

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    ports:
      - "8545:8545"
    entrypoint: ["anvil"]
    command:
      - --chain-id
      - "${ANVIL_CHAIN_ID:-1337}"
      - -a
      - "${ANVIL_ACCOUNTS:-10}"
      - -m
      - "${ANVIL_MNEMONIC:-myth like bonus scare over problem client lizard pioneer submit female collect}"
    healthcheck:
      test: bash -c "echo 'hello' > /dev/tcp/localhost/8545"
